### ISSUE TITLE
Add support for overriding iOS injected tel: links

### ISSUE THREAD

**Issue by DrizzlyOwl** [Mixd/frontend-framework#17]
I propose to add an entry into `base/_typography.scss` which will override the default behaviour of iOS wherein the browser will automatically style a phone number as an anchor link even if it is unintended. 

This snippet is an improvement to simply reset the styles to inherit the parent element or a previously defined style for standard anchors.

```css
p > a[href^="tel"]{
    color: inherit;
    text-decoration: none;
}
```
